# Change these first
owner: zeroxonef # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Jellyfin
    url: https://jellyfin.dmpstr.top
  - name: Authentik
    url: http://ak.dmpstr.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dmpstr.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Jade's service(s) status page"
  introMessage: Hosted mostly on an optiplex
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
